matrix:
  allow_failures:
    - env: GHCVER=head
    - env: HPVER=2013.2.0.0

env:
 - GHCVER=7.6.3
 - GHCVER=7.8.1
 - GHCVER=7.8.2
 - GHCVER=7.8.3
 - GHCVER=head
 - HPVER=2013.2.0.0

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install cabal-install-1.20 ghc-$GHCVER libicu-dev
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
 - cabal-1.20 update
 - travis_retry cabal-1.20 install Cabal

script:
 - travis_retry cabal-1.20 install --only-dependencies --reorder-goals
 - cabal-1.20 install -j1 --enable-tests

notifications:
  irc: "chat.freenode.net#yi"